---
- name: install depences
  yum: name={{ item }}
  with_items:
    - postfix
    - cronie

- name: start postfix automatically
  service: >
    name=postfix
    state=running
    enabled=yes

- name: get rpm
  get_url:
    url={{ gitlab_rpm_dir }}/{{ gitlab_rpm_file }}
    dest=/usr/local/src/{{ gitlab_rpm_file }}

- name: install GitLab
  yum: name=/usr/local/src/{{ gitlab_rpm_file }}
  notify: reconfigure gitlab

- name: put gitlab config
  template:
    src=etc/gitlab/gitlab.rb.j2
    dest=/etc/gitlab/gitlab.rb
    mode=0600
  notify: reconfigure gitlab

- name: create directory for ssl files
  file:
    path=/etc/gitlab/ssl
    state=directory
    mode=0700
  when: '"https:" in gitlab_external_url'

- name: put ssl files
  copy:
    src={{ item }}
    dest=/etc/gitlab/ssl
    mode=0600
  with_fileglob:
    - etc/gitlab/ssl/*.pem.develop
  when: '"https:" in gitlab_external_url'

- name: copy ssl files
  shell:
    for src in `ls -1 *.develop`; do
      dest=`echo $src | sed -e 's/\.develop$//'`;
      test -f $dest || cp -pv $src $dest;
    done
    chdir=/etc/gitlab/ssl
  when: '"https:" in gitlab_external_url'
  register: result
  changed_when: result.stdout != ""
  notify: restart nginx
